bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = "images"

urlpatterns = [
    path("create/", views.image_create, name="create"),
    path('detail/<int:id>/<slug:slug>/',views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),

]

bookmarks/images/models.py
from django.db import models

# Create your models here.

bookmarks/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["title", "url", "description"]
        widgets = {"url": forms.HiddenInput}

    def clean_url(self):
        url = self.cleaned_data["url"]
        valid_extensions = ["jpg", "jpeg"]
        extention = url.split(".", 1)[1].lower()
        if extention not in valid_extensions:
            raise forms.ValidationError(
                "The given URL does not " "match valid image extensions."
            )
        return url
    def save(self, force_update=False, force_insert=False, commit=True):
        image_obj = super().save(commit=False)
        image_url = self.cleaned_data["url"]
        name = slugify(image_obj.title)
        extension = image_url.rsplit(".", 1)[1].lower()
        image_name = f"{name}.{extension}"
        response = request.urlopen(image_url)
        image_obj.image.save(image_name, ContentFile(response), save=False)
        if commit:
            image_obj.save()
        return image_obj

bookmarks/images/views.py
from .models import Image
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import ImageCreateForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import HttpResponse


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 5)
    page = request.GET.get("page")
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(
            request,
            "images/image/list_ajax.html",
            {"section": "images", "images": images},
        )
    return render(
        request,
        "images/image/list.html",
        {"section": "images", "images": images},
    )


@login_required
def image_create(request):
    if request.method == "POST":
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            messages.success(request, "Image added successfully")

            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)

    return render(
        request,
        "images/image/create.html",
        {"section": "images", "form": form},
    )

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request,'images/image/detail.html',{'section': 'images',
        'image': image})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get("id")
    action = request.POST.get("action")
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == "like":
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({"status": "ok"})
        except Exception:
            pass
    return JsonResponse({"status": "error"})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{ request.GET.url }}" class="image-preview">
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
  </form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  
    <a href="{{ image.image.url }}">
        <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    </a>

  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in users_like %}
        <div>
          <img src="{{ user.profile.photo.url }}">
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}
{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');
          toggle_link_action(previous_action)
          toggle_link_text(previous_action)
          update_total_likes(previous_action);
        }
      }
    );
  });
function update_total_likes(previous_action){
    var previous_likes = parseInt($('span.count .total').text());
    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
}

function toggle_link_action(previous_action){
    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
}

function toggle_link_text(previous_action){
    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
}
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
    {% include "images/image/list_ajax.html" %}
</div>
{% endblock %}
{% block domready %}
  var page = 1;
  var is_last_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && is_last_page == false &&
    block_request == false) {
     block_request = true;
      page += 1;
      append_image(page,is_last_page,block_request)
    }
  });
  function append_image(page,is_last_page,block_request){
    $.get('?page=' + page, function(data) {
      if(data == '') {
         is_last_page = true;
       }
       else {
         block_request = false;
         $('#image-list').append(data);
       }
     });
  }
{% endblock %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
<div class="image">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
        </a>
    </a>
    <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">
        {{ image.title }}
        </a>
    </div>
</div>
{% endfor %}